// PDF Export Module
const PDFExport = {
    // Initialize PDF export functionality
    init() {
        window.jsPDF = window.jspdf.jsPDF;
    },

    // Generate PDF from report content
    async generatePDF(reportContent, reportType, config) {
        const pdf = new jsPDF({
            orientation: 'portrait',
            unit: 'mm',
            format: 'a4'
        });

        // Convert report content to canvas
        const canvas = await html2canvas(reportContent, {
            scale: 2,
            logging: false,
            useCORS: true
        });

        // PDF dimensions
        const pdfWidth = pdf.internal.pageSize.getWidth();
        const pdfHeight = pdf.internal.pageSize.getHeight();
        
        // Add header
        this.addHeader(pdf, reportType, config);
        
        // Convert canvas to image
        const imgData = canvas.toDataURL('image/png');
        
        // Calculate image dimensions to fit page
        const imgWidth = canvas.width;
        const imgHeight = canvas.height;
        const ratio = Math.min(pdfWidth / imgWidth, (pdfHeight - 40) / imgHeight);
        
        // Add image to PDF
        pdf.addImage(
            imgData, 
            'PNG', 
            0, 
            40, 
            imgWidth * ratio, 
            imgHeight * ratio
        );

        // Add footer
        this.addFooter(pdf);

        // Save the PDF
        const fileName = this.generateFileName(reportType, config);
        pdf.save(fileName);
    },

    // Add header to PDF
    addHeader(pdf, reportType, config) {
        // Set font styles
        pdf.setFont('helvetica', 'bold');
        pdf.setFontSize(16);
        
        // Add title
        const title = this.generateTitle(reportType, config);
        pdf.text(title, 10, 20);
        
        // Add metadata
        pdf.setFont('helvetica', 'normal');
        pdf.setFontSize(10);
        
        const date = new Date().toLocaleDateString();
        const metadata = this.generateMetadata(reportType, config);
        pdf.text(`Generated on: ${date}`, 10, 30);
        pdf.text(metadata, 10, 35);
    },

    // Add footer to PDF
    addFooter(pdf) {
        const pageCount = pdf.internal.getNumberOfPages();
        pdf.setFont('helvetica', 'italic');
        pdf.setFontSize(8);
        
        for (let i = 1; i <= pageCount; i++) {
            pdf.setPage(i);
            pdf.text(
                'Generated by EduPaper Pro',
                pdf.internal.pageSize.getWidth() / 2,
                pdf.internal.pageSize.getHeight() - 10,
                { align: 'center' }
            );
            pdf.text(
                `Page ${i} of ${pageCount}`,
                pdf.internal.pageSize.getWidth() - 20,
                pdf.internal.pageSize.getHeight() - 10,
                { align: 'right' }
            );
        }
    },

    // Generate title for PDF
    generateTitle(reportType, config) {
        switch (reportType) {
            case 'student':
                return `Student Performance Report - ${config.student || 'All Students'}`;
            case 'question':
                return `Question Analytics Report - ${config.subject || 'All Subjects'}`;
            case 'class':
                return `Class Progress Report - ${config.class || 'All Classes'}`;
            default:
                return 'EduPaper Pro Report';
        }
    },

    // Generate metadata string
    generateMetadata(reportType, config) {
        const metadata = [];
        
        switch (reportType) {
            case 'student':
                metadata.push(
                    `Time Period: ${config.timePeriod || 'All Time'}`,
                    `Subject: ${config.subject || 'All Subjects'}`,
                    `Report Format: ${config.format || 'Detailed'}`
                );
                break;
            case 'question':
                metadata.push(
                    `Subject: ${config.subject || 'All Subjects'}`,
                    `Chapter: ${config.chapter || 'All Chapters'}`,
                    `Difficulty: ${config.difficulty || 'All Levels'}`
                );
                break;
            case 'class':
                metadata.push(
                    `Class: ${config.class || 'All Classes'}`,
                    `Section: ${config.section || 'All Sections'}`,
                    `Time Period: ${config.timePeriod || 'All Time'}`
                );
                break;
        }
        
        return metadata.join(' | ');
    },

    // Generate filename for PDF
    generateFileName(reportType, config) {
        const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
        const prefix = 'edupaper-pro';
        const type = reportType.toLowerCase();
        const identifier = this.getIdentifier(reportType, config);
        
        return `${prefix}-${type}-${identifier}-${timestamp}.pdf`.toLowerCase();
    },

    // Get identifier for filename
    getIdentifier(reportType, config) {
        switch (reportType) {
            case 'student':
                return config.student?.toLowerCase().replace(/\s+/g, '-') || 'all-students';
            case 'question':
                return config.subject?.toLowerCase().replace(/\s+/g, '-') || 'all-subjects';
            case 'class':
                return config.class?.toLowerCase().replace(/\s+/g, '-') || 'all-classes';
            default:
                return 'report';
        }
    }
};

// Export the module
window.PDFExport = PDFExport;
